version: '3'  # Docker Composeのバージョン
services:
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - ./code:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    env_file: docker-compose.env
    command: python manage.py runserver 0.0.0.0:8000