# Generated by Django 2.2.2 on 2020-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streamerName', models.TextField()),
            ],
        ),
    ]
